In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

## Read the dataset

In [3]:
df = pd.read_csv('../Dataset/fifa21_data_set.csv')

In [11]:
df.head(5)

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,ID,...,PAS,DRI,DEF,PHY,Hits,Month,Day,Year,Contract,Team
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,158023,...,91,95,38,65,372,Jul,1,2004,2004 ~ 2021,FC Barcelona
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,...,81,89,35,77,344,Jul,10,2018,2018 ~ 2022,Juventus
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,200389,...,78,90,52,90,86,Jul,16,2014,2014 ~ 2023,Atlético Madrid
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,...,93,88,64,78,163,Aug,30,2015,2015 ~ 2023,Manchester City
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,190871,...,86,94,36,59,273,Aug,3,2017,2017 ~ 2022,Paris Saint-Germain

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 80 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   photoUrl          18979 non-null  object
 1   LongName          18979 non-null  object
 2   playerUrl         18979 non-null  object
 3   Nationality       18979 non-null  object
 4   Positions         18979 non-null  object
 5   Name              18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   ID                18979 non-null  int64
 10  Height            18979 non-null  float64
 11  Weight            18979 non-null  int64
 12  foot              18979 non-null  object
 13  BOV               18979 non-null  int64
 14  BP                18979 non-null  object
 15  Growth            18979 non-null  int64
 16  Loan Date End     1013 non-null   object
 17  Value             18979 non-null  float64
 18  Wage              18979 non-null  int64
 19  Release Clause    18979 non-null  int64
 20  Attacking         18979 non-null  int64
 21  Crossing          18979 non-null  int64
 22  Finishing         18979 non-null  int64
 23  Heading Accuracy  18979 non-null  int64
 24  Short Passing     18979 non-null  int64
 25  Volleys           18979 non-null  int64
 26  Skill             18979 non-null  int64
 27  Dribbling         18979 non-null  int64
 28  Curve             18979 non-null  int64
 29  FK Accuracy       18979 non-null  int64
 30  Long Passing      18979 non-null  int64
 31  Ball Control      18979 non-null  int64
 32  Movement          18979 non-null  int64
 33  Acceleration      18979 non-null  int64
 34  Sprint Speed      18979 non-null  int64
 35  Agility           18979 non-null  int64
 36  Reactions         18979 non-null  int64
 37  Balance           18979 non-null  int64
 38  Power             18979 non-null  int64
 39  Shot Power        18979 non-null  int64
 40  Jumping           18979 non-null  int64
 41  Stamina           18979 non-null  int64
 42  Strength          18979 non-null  int64
 43  Long Shots        18979 non-null  int64
 44  Mentality         18979 non-null  int64
 45  Aggression        18979 non-null  int64
 46  Interceptions     18979 non-null  int64
 47  Positioning       18979 non-null  int64
 48  Vision            18979 non-null  int64
 49  Penalties         18979 non-null  int64
 50  Composure         18979 non-null  int64
 51  Defending         18979 non-null  int64
 52  Marking           18979 non-null  int64
 53  Standing Tackle   18979 non-null  int64
 54  Sliding Tackle    18979 non-null  int64
 55  Goalkeeping       18979 non-null  int64
 56  GK Diving         18979 non-null  int64
 57  GK Handling       18979 non-null  int64
 58  GK Kicking        18979 non-null  int64
 59  GK Positioning    18979 non-null  int64
 60  GK Reflexes       18979 non-null  int64
 61  Total Stats       18979 non-null  int64
 62  Base Stats        18979 non-null  int64
 63  W/F               18979 non-null  object
 64  SM                18979 non-null  object
 65  A/W               18979 non-null  object
 66  D/W               18979 non-null  object
 67  IR                18979 non-null  object
 68  PAC               18979 non-null  int64
 69  SHO               18979 non-null  int64
 70  PAS               18979 non-null  int64
 71  DRI               18979 non-null  int64
 72  DEF               18979 non-null  int64
 73  PHY               18979 non-null  int64
 74  Hits              18979 non-null  int64
 75  Month             18979 non-null  object
 76  Day               18979 non-null  int64
 77  Year              18979 non-null  int64
 78  Contract          17728 non-null  object
 79  Team              18745 non-null  object
dtypes: float64(2), int64(61), object(17)
memory usage: 11.6+ MB

In [16]:
new_df = df[['Name', 'Age', 'Height', 'Weight', 'foot', 'Penalties', 'Wage', 'Finishing', 'Attacking', 'Long Passing', 'Skill', 'Dribbling', 'Acceleration', 'Sprint Speed', 'Shot Power', 'Long Shots', 'Value']]

In [20]:
new_df.head(10)

,Name,Age,Height,Weight,foot,Penalties,Wage,Finishing,Attacking,Long Passing,Skill,Dribbling,Acceleration,Sprint Speed,Shot Power,Long Shots,Value
0,L. Messi,33,5.70,159,Left,75,560,95,429,91,470,96,91,80,86,94,67500000.0
1,Cristiano Ronaldo,35,6.20,183,Right,84,220,95,437,77,414,88,87,91,94,93,46000000.0
2,J. Oblak,27,6.20,192,Right,11,125,11,95,40,109,12,43,60,59,12,75000000.0
3,K. De Bruyne,29,5.11,154,Right,84,370,82,407,93,441,88,77,76,91,91,87000000.0
4,Neymar Jr,28,5.90,150,Right,92,270,87,408,81,448,95,94,89,80,84,90000000.0
5,R. Lewandowski,31,6.00,176,Right,88,240,94,423,70,407,85,77,78,89,85,80000000.0
6,K. Mbappé,21,5.10,161,Right,70,160,91,408,70,394,92,96,96,86,79,105500000.0
7,Alisson,27,6.30,201,Right,23,160,13,114,44,138,27,56,47,64,14,62500000.0
8,M. Salah,28,5.90,157,Left,83,250,91,392,75,406,90,94,92,80,84,78000000.0
9,S. Mané,28,5.90,152,Right,71,250,90,410,71,391,91,95,93,84,78,78000000.0

In [33]:
new_df.describe()

,Age,Height,Weight,Penalties,Wage,Finishing,Attacking,Long Passing,Skill,Dribbling,Acceleration,Sprint Speed,Shot Power,Long Shots,Value
count,18979.000000,18979.000000,18979.00000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,1.897900e+04
mean,25.194583,5.797480,165.38785,48.058328,131.795932,45.842932,248.938616,52.725012,256.481848,55.587913,64.357922,64.413088,57.802413,46.786343,2.228953e+06
std,4.710753,0.449354,15.58793,15.655890,246.867833,19.566978,74.299764,15.177695,78.652897,18.761660,14.890208,14.638874,13.308980,19.300862,5.097614e+06
min,16.000000,5.100000,110.00000,6.000000,0.000000,3.000000,42.000000,5.000000,40.000000,5.000000,13.000000,12.000000,18.000000,4.000000,0.000000e+00
25%,21.000000,5.110000,154.00000,39.000000,2.000000,30.000000,222.000000,43.000000,222.000000,49.000000,57.000000,57.000000,48.000000,32.000000,3.000000e+05
50%,25.000000,5.900000,165.00000,49.000000,6.000000,49.000000,263.000000,56.000000,269.000000,61.000000,67.000000,67.000000,59.000000,51.000000,6.500000e+05
75%,29.000000,6.100000,176.00000,60.000000,41.000000,62.000000,297.000000,64.000000,310.000000,68.000000,74.000000,74.000000,68.000000,62.000000,1.800000e+06
max,53.000000,6.900000,243.00000,92.000000,950.000000,95.000000,437.000000,93.000000,470.000000,96.000000,97.000000,96.000000,95.000000,94.000000,1.055000e+08

In [34]:
new_df.isnull()

,Name,Age,Height,Weight,foot,Penalties,Wage,Finishing,Attacking,Long Passing,Skill,Dribbling,Acceleration,Sprint Speed,Shot Power,Long Shots,Value
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18975,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18976,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18977,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18978,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [35]:
new_df.isnull().sum()

Name            0
Age             0
Height          0
Weight          0
foot            0
Penalties       0
Wage            0
Finishing       0
Attacking       0
Long Passing    0
Skill           0
Dribbling       0
Acceleration    0
Sprint Speed    0
Shot Power      0
Long Shots      0
Value           0
dtype: int64

In [41]:
new_df.columns

Index(['Name', 'Age', 'Height', 'Weight', 'foot', 'Penalties', 'Wage',
       'Finishing', 'Attacking', 'Long Passing', 'Skill', 'Dribbling',
       'Acceleration', 'Sprint Speed', 'Shot Power', 'Long Shots', 'Value'],
      dtype='object')

In [45]:
for i in new_df:
    print("{}".format(i))
    print(new_df[i].unique())
    print("\n")
    pass

Name
['L. Messi' 'Cristiano Ronaldo' 'J. Oblak' ... 'Xia Ao' 'B. Hough'
 'M. Flores']


Age
[33 35 27 29 28 31 21 34 32 25 26 30 20 24 22 23 19 38 42 37 36 18 39 17
 40 41 16 43 53]


Height
[5.7  6.2  5.11 5.9  6.   5.1  6.3  6.4  6.1  6.6  5.8  5.6  6.5  5.5
 5.4  6.7  5.2  5.3  6.8  6.9 ]


Weight
[159 183 192 154 150 176 161 201 157 152 203 187 185 212 179 181 165 190
 196 163 168 141 172 198 146 132 207 174 148 143 130 134 194 205 214 170
 137 139 209 220 128 216 227 218 123 225 223 126 121 229 236 243 117 110
 119 115]


foot
['Left' 'Right']


Penalties
[75 84 11 92 88 70 23 83 71 62 25 66 27 47 54 44 86 17 69 90 33 87 73 60
 55 68 91 72 78 18 82 40 50 45 43 64 29 59 24 56 46 81 49 61 67 74 63 58
 79 80 38 32 41 76 77 20 85 19 26 21 52 34 53 65 57 16 42 89 14 15 13 22
 51 37  9 48 31 12 36 39 10 30 35 28  8  7  6]


Wage
[560 220 125 370 270 240 160 250 210 260 310 350 300 190 145 195 140 100
  82 110 230 155 200 165 290 170 105 115  94 135 150 130  93  55  58  80
  34 120  99  92  59  65  56  98  47  96  18  70  75  84  27  20  86  77
  74  91  25  46  67  85 175  90  79  83  54  43  49  45  41 500  39  38
  23  87  57  51  50  95  73  78  69  30  31  53  63  35  71  21  14  17
  33  28  32  89  68  36  64  26  72  48  76  40  29  16  37  24  97   0
  62  19  60  42  66  13  12  81  61  22  11  52  44  15   7  10   8   6
   9   5   3   4   2   1 950 550 900 650 700 600 800 750 850]


Finishing
[95 11 82 87 94 91 13 90 52 14 64 88 65 66 84 85 22 76 10 81 56 79 57 45
 77 63 80 86 15 93 67 12 72 92 33 51 46 60 75 73 55 50 42 83 39  9 68 48
 40 70 37 69 78 25 53 89  8 71 62 74 44 26 19 32 18 61 58 30 36 54 16 38
 29 59 34 27 47 20 43 31 49 41 28  5  7  6 21 17 35 23 24  4  3]


Attacking
[429 437  95 407 408 423 114 392 410 316 118 349  86 119 426 374 411 328
 383 405 123 360 420 224 388 397 373 365 371 311 396 345 400 399 425  78
 394 330 403 379 380  94 280 390 339 293 344 419 372 377  84 359 308 277
 346 382 363 389 402 292 352 298 368 366 386 361  91 364 385 341 305 355
 322 356 387 321  93 262 375 253 353 391 285 367 256 295 378  90 331  85
 338  69 105 350 358 319 343 302 271 113 340 393 247 406 342 334 351 258
  98 301 115 384  92 208  72  74 376 362 329 417 354  99  88 279  55 101
 263 395 100  87  81  82 310 318 409 117 323 348 381 315 248 327 309 130
 283 336 369  97 290 370 126 251 335 108 106 252 320 297 284  80  75 357
 270 306 337  73 286 326 324 325 103 333 259 273  61 296 313 312 347 401
 278 304  83  43 314 291  54 264 272 231 250 268 317 261 255  70 281 265
 299 287  68 294  77 219 332 269 300 289 282 288 107 122 244 274 112 276
  89 229 307 102 239  96 109 257 125  76 241 254 227 228 233 246 110 215
 124 245 242 214 266 275  67 104  63 303  66 230 260  50 111 238 249 240
 221 237 223  56 267 235 234 243 232 203  64 213 222 226 225 211 173  52
 207 236 217  57  71 204 216  59 199  60 189 194 116 205 201 193  65 192
 209 218 128 210  45  79 206  49 162 220 197 202 212 190  58 181  51  62
 200 198 195 191 131 185  42 180 182 196 188 169 178 187  53 183 184 186
 165 172  47 171 159 176  46 179 175 167 174 161 170 177 164 134 168 163
 166 158 150  48 143 152 160 148 151 157 154 141 146 147 149 156 153 138
 145 142 139 155 144 137 136]


Long Passing
[91 77 40 93 81 70 44 75 71 86 63 84 35 59 73 83 64 79 69 68 89 76 80 87
 82 37 53 36 50 65 48 74 47 78 31 24 85 55 54 90 49 32 62 67 66 51 52 28
 46 72 56 41 45 22 88 61 33 12 60 17 16 27 23 29 38 34 58 25 39 21 30 42
 43 57 20 26 19 18 13 15 11 14  9 10  5  8]


Skill
[470 414 109 441 448 407 394 138 406 391 363 144 369 110 160 404 381 397
 336 400 436 157 387 395 262 427 432 100 380 426 411 358 351 433 365 403
 429  98 341 386 383  99 413 115 276 330 359 309 435 143 375 355  96 420
 325 388 319 269 399 106 409 412 402 297 352 372 425 312 418 430 116 371
 428 439 422 104 345 295 405 440 349 396 252 417 401 233 377 382 251 368
 271 342 410  84 356 350 103  83 126 370 362 328 344 343 378 275 415 416
 119 127 317  77 393 373 408 348 384 334 376 300 107 220  89  72 390 419
 339 281  73 385 354 102 305 289  91 421  97 292 139 398 105 306 337 340
 101 335 302 123 113 122 347 250 364 333 323 389 361 322  86 338 367 258
 392  92  90 310 331  82 245 324 346 121 260 379 299 284 296 283 320 108
 278 286 315 274  88 114 264 366 326 288  94 117 360 125 424 318  93 124
 249 327  75 332 303 374 272 357 239 266 321 353 277 268 314 294 240  95
 227 112 118 263 280 140 282  81 329 201 313 221 257  87 285 316 287 270
 256 307 311 247 228 254  85 290 293  80 130 232 213 298 301 219 171 242
 267 216 291 168 261 308 246 273 237 279 248 253 208  78 255 230 243 210
  74 231 235 259 199 224 206 304 226  61 222 129 141 223 241 149 131 225
 189  71 265  70 179 192 120 134 209 177 173 212 236 238 218  76  69 234
 204 229 203 215 211 195 165 202 194  64 190  67 193 244 205  79 214 196
 111 187  65 200 198  63 217  68 184 135 167 148 207 142 185 133 191 197
 181  43  66 182  51 175 180 169 186 137 188 176 132  60 178 147 163 183
 162 152 170 172 174 159 161 154 153 128  62 166  53 155  56 151 164 158
  46 150  59  55  58 156 146  52 136  54  47  48 145  40  57]


Dribbling
[96 88 12 95 85 92 27 90 91 70 21 69 13 30 87 65 79 83 23 80 93 18 77 63
 76 16 81 11 84 10 59 78 55 75 15 86 66 67 28 57 82 64 19 62 53 72 26 50
 43 89 73 20 14 68 22 54 74 71 56  9 61 60 24 25  8 47 17 58 46 42 51 52
 49 44 35 48 39 29 40 45 34 33 31 41 32 38 36  7 37  5  6]


Acceleration
[91 87 43 77 94 96 56 95 72 38 60 42 54 79 89 64 66 73 57 51 86 85 78 80
 82 40 76 65 90 68 88 46 48 70 93 84 83 74 92 55 52 58 59 62 81 67 71 69
 44 53 50 45 49 41 75 61 63 35 47 34 36 37 39 30 97 31 32 33 27 28 26 29
 25 17 19 24 15 23 21 20 22 16 18 13 14]


Sprint Speed
[80 91 60 76 89 78 96 47 92 93 79 50 69 52 72 70 66 82 63 90 77 86 55 81
 83 85 65 68 53 43 94 62 87 61 58 88 67 54 64 75 95 73 84 56 49 44 74 57
 51 46 59 71 37 42 34 33 30 35 48 39 45 40 18 38 41 27 32 29 28 36 26 31
 22 25 15 20 23 17 16 24 19 21 12 14]


Shot Power
[86 94 59 91 80 89 64 84 81 66 88 56 68 79 71 78 82 70 55 76 61 83 51 87
 52 90 77 72 62 74 50 57 58 85 60 75 67 93 65 46 69 54 41 73 40 53 95 43
 63 42 48 31 44 37 49 39 45 38 47 30 34 33 25 36 28 27 32 26 35 23 22 29
 20 24 21 18]


Long Shots
[94 93 12 91 84 85 79 14 78 64 10 81 17 16 65 87 18 86 15 19 63 74 76 47
 89 70 77 90 82 13 80 54 88 49 53 58 66 75 51 73 30 61 46 35 83 71 72 69
 43 48 62 41 60 11 26 57 59 68 67  7 56 27 20 52 50 92 22 40 39 44 31 42
  9  6 55 38 23 28 24 25 34 36 29  8  4 45 33 21 37 32  5]


Value
[6.750e+07 4.600e+07 7.500e+07 8.700e+07 9.000e+07 8.000e+07 1.055e+08
 6.250e+07 7.800e+07 7.550e+07 6.950e+07 5.950e+07 5.600e+07 2.900e+07
 5.300e+07 2.450e+07 5.100e+07 6.500e+07 7.100e+07 5.350e+07 7.250e+07
 5.000e+07 5.800e+07 5.500e+07 1.600e+07 6.000e+07 6.300e+07 5.450e+07
 5.200e+07 5.250e+07 5.050e+07 2.700e+07 4.850e+07 3.800e+07 4.500e+07
 3.400e+07 3.900e+07 3.150e+07 1.550e+07 2.800e+07 4.650e+07 4.200e+07
 3.200e+07 3.650e+07 3.300e+07 2.850e+07 2.250e+07 2.100e+07 3.450e+07
 5.700e+07 4.950e+07 4.450e+07 4.400e+07 4.150e+07 4.900e+07 5.150e+07
 3.950e+07 4.750e+07 3.750e+07 4.050e+07 3.350e+07 3.700e+07 3.050e+07
 2.600e+07 1.800e+07 1.450e+07 3.550e+07 2.400e+07 1.150e+07 4.100e+07
 4.250e+07 3.000e+07 3.600e+07 3.100e+07 2.750e+07 3.500e+07 3.850e+07
 2.300e+07 2.500e+07 2.950e+07 2.550e+07 3.250e+07 1.900e+07 1.950e+07
 2.350e+07 1.500e+07 1.700e+07 1.100e+07 9.500e+06 2.200e+07 1.650e+07
 1.850e+07 1.750e+07 2.150e+07 2.050e+07 1.350e+07 2.000e+07 1.200e+07
 1.250e+07 7.000e+06 2.650e+07 1.400e+07 8.000e+06 2.200e+06 0.000e+00
 1.050e+07 1.300e+07 8.500e+06 4.800e+06 6.500e+06 3.600e+06 5.500e+06
 9.000e+06 3.000e+06 5.000e+06 4.500e+06 1.000e+07 4.000e+06 7.500e+06
 4.700e+06 6.000e+06 4.400e+06 1.300e+06 2.700e+06 4.200e+06 2.100e+06
 3.100e+06 4.900e+06 3.700e+06 4.300e+06 1.700e+06 1.500e+06 3.300e+06
 3.900e+06 1.900e+06 2.400e+06 9.000e+05 3.400e+06 4.100e+06 1.600e+06
 7.750e+05 2.600e+06 3.500e+06 2.900e+06 3.200e+06 1.200e+06 1.800e+06
 2.300e+06 1.100e+06 6.750e+05 2.500e+06 1.400e+06 4.600e+06 2.000e+06
 5.750e+05 9.500e+05 1.000e+06 3.800e+06 2.800e+06 4.000e+05 8.750e+05
 8.000e+05 3.250e+05 5.250e+05 8.500e+05 6.250e+05 9.750e+05 2.400e+05
 6.500e+05 8.250e+05 7.250e+05 4.750e+05 5.000e+05 7.500e+05 4.250e+05
 7.000e+05 3.500e+05 1.800e+05 5.500e+05 9.250e+05 3.000e+05 2.000e+05
 2.100e+05 1.100e+05 2.750e+05 1.400e+05 2.300e+05 4.500e+05 3.750e+05
 1.900e+05 9.000e+04 6.000e+05 1.300e+05 1.200e+05 1.500e+05 1.600e+05
 2.200e+05 8.000e+04 1.700e+05 7.000e+04 2.500e+05 5.000e+04 1.000e+05
 4.500e+04 3.500e+04 6.000e+04 3.000e+04 2.500e+04 4.000e+04 2.000e+04
 1.500e+04 1.000e+04 8.000e+03 5.000e+03]

## Agrregation with GroupBy

In [66]:
gr_name = new_df.groupby("Sprint Speed")

In [65]:
new_df.head(10)

,Name,Age,Height,Weight,foot,Penalties,Wage,Finishing,Attacking,Long Passing,Skill,Dribbling,Acceleration,Sprint Speed,Shot Power,Long Shots,Value
0,L. Messi,33,5.70,159,Left,75,560,95,429,91,470,96,91,80,86,94,67500000.0
1,Cristiano Ronaldo,35,6.20,183,Right,84,220,95,437,77,414,88,87,91,94,93,46000000.0
2,J. Oblak,27,6.20,192,Right,11,125,11,95,40,109,12,43,60,59,12,75000000.0
3,K. De Bruyne,29,5.11,154,Right,84,370,82,407,93,441,88,77,76,91,91,87000000.0
4,Neymar Jr,28,5.90,150,Right,92,270,87,408,81,448,95,94,89,80,84,90000000.0
5,R. Lewandowski,31,6.00,176,Right,88,240,94,423,70,407,85,77,78,89,85,80000000.0
6,K. Mbappé,21,5.10,161,Right,70,160,91,408,70,394,92,96,96,86,79,105500000.0
7,Alisson,27,6.30,201,Right,23,160,13,114,44,138,27,56,47,64,14,62500000.0
8,M. Salah,28,5.90,157,Left,83,250,91,392,75,406,90,94,92,80,84,78000000.0
9,S. Mané,28,5.90,152,Right,71,250,90,410,71,391,91,95,93,84,78,78000000.0

In [84]:
gr_name['Skill'].max().reset_index().tail(30)

    Sprint Speed  Skill
54            67    420
55            68    432
56            69    420
57            70    428
58            71    417
59            72    430
60            73    417
61            74    416
62            75    415
63            76    441
64            77    425
65            78    422
66            79    435
67            80    470
68            81    395
69            82    436
70            83    432
71            84    425
72            85    417
73            86    427
74            87    414
75            88    388
76            89    448
77            90    400
78            91    414
79            92    406
80            93    410
81            94    383
82            95    402
83            96    394